# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 메시지 ID')),
                ('speaker', models.CharField(choices=[('USER', '사용자'), ('AI', 'AI')], max_length=10, verbose_name='화자')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지들',
                'db_table': 'chatbot_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 세션 ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '챗봇 세션',
                'verbose_name_plural': '챗봇 세션들',
                'db_table': 'chatbot_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
