# Generated by Django 4.2.23 on 2025-08-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0002_documentscrap_created_at_alter_document_created_at'),
        ('user', '0004_remove_usercategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 세션 ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성 상태')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_session', to='document.document', verbose_name='연결된 공문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '챗봇 세션',
                'verbose_name_plural': '챗봇 세션들',
                'db_table': 'chatbot_session',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'document')},
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 메시지 ID')),
                ('speaker', models.CharField(choices=[('USER', '사용자'), ('AI', 'AI')], max_length=10, verbose_name='화자')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatbotsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지들',
                'db_table': 'chatbot_message',
                'ordering': ['created_at'],
            },
        ),
    ]
