# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='user.user', verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='chatbot_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatbotsession', verbose_name='세션'),
        ),
        migrations.AlterUniqueTogether(
            name='chatbotsession',
            unique_together={('user', 'document')},
        ),
    ]
