# Generated by Django 4.2.23 on 2025-08-07 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True, verbose_name='카테고리ID')),
                ('category_name', models.CharField(max_length=64, unique=True, verbose_name='카테고리명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리들',
                'db_table': 'category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='사용자ID')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('OTHER', '기타')], max_length=10, null=True, verbose_name='성별')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user_region_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='사용자지역ID')),
                ('region_id', models.CharField(max_length=50, verbose_name='지역ID')),
                ('type', models.CharField(choices=[('거주지', '거주지'), ('관심지역', '관심지역')], max_length=20, verbose_name='지역 타입')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_regions', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 관심 지역',
                'db_table': 'user_region',
                'unique_together': {('user', 'region_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user_category_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='사용자카테고리ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 관심 주제',
                'db_table': 'user_category',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
