# Generated by Django 4.2.23 on 2025-08-07 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='김덕사', help_text='사용자 실명', max_length=64, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='user_category_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='사용자카테고리ID'),
        ),
        migrations.AlterField(
            model_name='userregion',
            name='user_region_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='사용자지역ID'),
        ),
    ]
