# Generated by Django 4.2.23 on 2025-08-07 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name_alter_usercategory_user_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='user_category_id',
        ),
        migrations.RemoveField(
            model_name='userregion',
            name='user_region_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='사용자 이름', max_length=64, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='이름'),
        ),
    ]
