# Generated by Django 4.2.23 on 2025-08-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usercategory_user_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userregion',
            name='created_at',
        ),
    ]
