# Generated by Django 4.2.23 on 2025-08-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_region_city_alter_region_district_and_more'),
        ('user', '0004_remove_usercategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='userregion',
            name='region_id',
        ),
        migrations.AddField(
            model_name='userregion',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='지역'),
            preserve_default=False,
        ),
    ]
