# Generated by Django 4.2.23 on 2025-08-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False, verbose_name='알림 ID')),
                ('title', models.CharField(max_length=128, verbose_name='알림 제목')),
                ('content', models.CharField(max_length=256, verbose_name='알림 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('notification_time', models.DateTimeField(auto_now_add=True, verbose_name='알림 생성 시간')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='document.document', verbose_name='공문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'db_table': 'notification',
                'ordering': ['-notification_time'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_d569bc_idx'), models.Index(fields=['notification_time'], name='notificatio_notific_9c41ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('registration_token', models.CharField(max_length=255, unique=True, verbose_name='FCM 등록 토큰')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10, verbose_name='디바이스 타입')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'FCM 디바이스',
                'verbose_name_plural': 'FCM 디바이스들',
                'db_table': 'fcm_device',
                'unique_together': {('user', 'registration_token')},
            },
        ),
    ]
