# Generated by Django 4.2.23 on 2025-08-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='알림 내용'),
        ),
    ]
