# Generated by Django 4.2.23 on 2025-08-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지역명')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='지역코드')),
                ('region_type', models.CharField(choices=[('sido', '시/도'), ('sigungu', '시/군/구')], max_length=10, verbose_name='지역타입')),
                ('full_name', models.CharField(max_length=100, verbose_name='전체명')),
                ('is_selectable', models.BooleanField(default=True, verbose_name='선택가능여부')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='region.region', verbose_name='상위지역')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'region',
                'ordering': ['code'],
            },
        ),
    ]
