# Generated by Django 4.2.23 on 2025-08-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_selectable',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_type',
        ),
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
    ]
