# Generated by Django 4.2.23 on 2025-08-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_alter_region_options_remove_region_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='region',
            name='district',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
