# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(db_column='document_id', primary_key=True, serialize=False, verbose_name='공문 ID')),
                ('doc_title', models.CharField(max_length=512, verbose_name='제목')),
                ('doc_content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('doc_type', models.CharField(blank=True, choices=[('PARTICIPATION', '참여'), ('NOTICE', '공지'), ('REPORT', '보고'), ('ANNOUNCEMENT', '공고')], max_length=64, null=True, verbose_name='타입')),
                ('pub_date', models.DateTimeField(verbose_name='게시일')),
                ('dead_date', models.DateTimeField(blank=True, help_text='참여 등의 공문만', null=True, verbose_name='마감일')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성 상태')),
                ('region_id', models.IntegerField(verbose_name='지역 ID')),
                ('image_url', models.CharField(blank=True, help_text='이미지 파일 URL 또는 경로', max_length=1024, null=True, verbose_name='이미지 URL')),
            ],
            options={
                'verbose_name': '공문',
                'verbose_name_plural': '공문들',
                'db_table': 'document',
                'ordering': ['-pub_date'],
            },
        ),
    ]
