# Generated by Django 4.2.23 on 2025-08-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_usercategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(db_column='document_id', primary_key=True, serialize=False, verbose_name='공문 ID')),
                ('doc_title', models.CharField(max_length=512, verbose_name='제목')),
                ('doc_content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('doc_type', models.CharField(blank=True, choices=[('PARTICIPATION', '참여'), ('NOTICE', '공지'), ('REPORT', '보고'), ('ANNOUNCEMENT', '공고')], max_length=20, null=True, verbose_name='타입')),
                ('pub_date', models.DateTimeField(verbose_name='게시일')),
                ('dead_date', models.DateTimeField(blank=True, help_text='참여 등의 공문만', null=True, verbose_name='마감일')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시')),
                ('region_id', models.IntegerField(verbose_name='지역 ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '공문',
                'verbose_name_plural': '공문들',
                'db_table': 'document',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScrap',
            fields=[
                ('id', models.AutoField(db_column='document_scrap_id', primary_key=True, serialize=False, verbose_name='공문 스크랩 ID')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='document.document', verbose_name='공문')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_scraps', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '공문 스크랩',
                'verbose_name_plural': '공문 스크랩들',
                'db_table': 'document_scrap',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
