# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents', to='user.category', verbose_name='카테고리'),
        ),
    ]
