# Generated by Django 4.2.23 on 2025-08-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='related_departments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
