# Generated by Django 4.2.23 on 2025-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usercategory_created_at_and_more'),
        ('document', '0002_documentscrap_created_at_alter_document_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents', to='user.category', verbose_name='카테고리'),
        ),
    ]
