# Generated by Django 4.2.23 on 2025-08-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_category_document_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentScrap',
        ),
    ]
