# Generated by Django 4.2.23 on 2025-08-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_keywords_document_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
