# Generated by Django 4.2.23 on 2025-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='원본 링크 URL'),
        ),
    ]
