# Generated by Django 4.2.23 on 2025-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_delete_documentscrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_url',
            field=models.CharField(blank=True, help_text='이미지 파일 URL 또는 경로', max_length=1024, null=True, verbose_name='이미지 URL'),
        ),
    ]
