# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotScrap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 스크랩 ID')),
                ('summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI 응답 요약')),
            ],
            options={
                'verbose_name': '챗봇 스크랩',
                'verbose_name_plural': '챗봇 스크랩들',
                'db_table': 'chatbot_scrap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScrap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(db_column='document_scrap_id', primary_key=True, serialize=False, verbose_name='공문 스크랩 ID')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='document.document', verbose_name='공문')),
            ],
            options={
                'verbose_name': '공문 스크랩',
                'verbose_name_plural': '공문 스크랩들',
                'db_table': 'document_scrap',
            },
        ),
    ]
