# Generated by Django 4.2.23 on 2025-08-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('user', '0004_remove_usercategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotScrap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗 스크랩 ID')),
                ('summary', models.CharField(blank=True, help_text='AI 응답을 한 줄로 요약', max_length=200, null=True, verbose_name='AI 응답 요약')),
                ('ai_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scraps', to='chatbot.chatbotmessage', verbose_name='AI 메시지')),
                ('chatbot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='chatbot.chatbotsession', verbose_name='세션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_scraps', to='user.user', verbose_name='사용자')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scraps', to='chatbot.chatbotmessage', verbose_name='사용자 메시지')),
            ],
            options={
                'verbose_name': '챗봇 스크랩',
                'verbose_name_plural': '챗봇 스크랩들',
                'db_table': 'chatbot_scrap',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'user_message', 'ai_message')},
            },
        ),
    ]
