# Generated by Django 4.2.23 on 2025-08-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usercategory_created_at_and_more'),
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotscrap',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='chatbotscrap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 스크랩 ID'),
        ),
    ]
