# Generated by Django 4.2.23 on 2025-08-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0003_initial'),
        ('scrap', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentscrap',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_scraps', to='user.user', verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='ai_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scraps', to='chatbot.chatbotmessage', verbose_name='AI 메시지'),
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='chatbot_scraps', to='user.category', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='chatbot_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='chatbot.chatbotsession', verbose_name='세션'),
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_scraps', to='user.user', verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='user_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scraps', to='chatbot.chatbotmessage', verbose_name='사용자 메시지'),
        ),
        migrations.AlterUniqueTogether(
            name='documentscrap',
            unique_together={('user', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='chatbotscrap',
            unique_together={('user', 'user_message', 'ai_message')},
        ),
    ]
