# Generated by Django 4.2.23 on 2025-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usercategory_created_at_and_more'),
        ('scrap', '0002_chatbotscrap_category_alter_chatbotscrap_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotscrap',
            name='category',
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='chatbot_scraps', to='user.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='chatbotscrap',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AI 응답 요약'),
        ),
    ]
