# Generated by Django 4.2.23 on 2025-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usercategory_created_at_and_more'),
        ('scrap', '0003_remove_chatbotscrap_category_chatbotscrap_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotscrap',
            name='categories',
        ),
        migrations.AddField(
            model_name='chatbotscrap',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='chatbot_scraps', to='user.category', verbose_name='카테고리'),
        ),
    ]
