# Generated by Django 4.2.23 on 2025-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_chatbotscrap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotscrap',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AI 응답 요약'),
        ),
    ]
