# Generated by Django 4.2.23 on 2025-08-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_remove_chatbotscrap_categories_chatbotscrap_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotscrap',
            old_name='category',
            new_name='categories',
        ),
    ]
