# Generated by Django 4.2.23 on 2025-08-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_delete_documentscrap'),
        ('user', '0005_remove_category_category_id_and_more'),
        ('scrap', '0005_rename_category_chatbotscrap_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScrap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('id', models.AutoField(db_column='document_scrap_id', primary_key=True, serialize=False, verbose_name='공문 스크랩 ID')),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='document.document', verbose_name='공문')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_scraps', to='user.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '공문 스크랩',
                'verbose_name_plural': '공문 스크랩들',
                'db_table': 'document_scrap',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
